In [10]:
# BASIC SIGMOID USING 'MATH' LIBRARY
import math

def basic_sigmoid(x):
    """
    Compute sigmoid of x.
    
    Arguments:
    x == A scalar
    
    Return: 
    s -- sigmoid(x)
    """
    
    s = 1 / (1 + math.exp(-x))
    
    return s

In [12]:
basic_sigmoid(3)

0.9525741268224334

In [13]:
x = [1,2,3]
basic_sigmoid(x)
#this errors because 'math' library uses real number
#this is why we use numpy because we mostly use matrices and vectors in deep learning

TypeError: bad operand type for unary -: 'list'

In [16]:
import numpy as np

x = np.array([1,2,3])

print(np.exp(x))
print(x + 3)

[ 2.71828183  7.3890561  20.08553692]
[4 5 6]


In [17]:
# SIGMOID USING NUMPY
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


In [18]:
sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

In [35]:
# SIGMOID GRADIENT

def sigmoid_derivative(x):
    """
        Compute the gradient (also called the slop or derivative) of the sigmoid function with respect to its input x.
    
        Arguments:
        x -- A scalar or numpy array
    
        Return:
        ds -- Your computed gradient.
    """

    s = sigmoid(x)
    
    ds = s*(1-s)
    
    return ds
    

In [34]:
# from above: x = np.array([1,2,3])

print("sigmoid_derivative(x) = " + str(sigmoid_derivative(x)))

[1 2 3]
[0.73105858 0.88079708 0.95257413]
sigmoid_derivative(x) = [0.19661193 0.10499359 0.04517666]


In [63]:
# WORKING WITH IMAGE VECTORS

"""
images are represented by a 3D array of shape(length, height, depth = 3) but when you read an image as the input 
of an algorithm you convert it to a vector of shape(length*height*3,1).  In other words, you unroll or reshape it
into a 1D vector
"""

def image2vector(image):
    """
    Argument:
    image -- a numpy array of shape (length, height, depth)
    
    Returns:
    v -- a vector of shape (length*height*depth,1)
    """
    
    print(image.shape)
    
    v = image.reshape((image.shape[0]*image.shape[1]*image.shape[2]),1)
    
    return v

In [64]:
pic1 = np.array([
    [[ 0.67826139,  0.29380381],
     [ 0.90714982,  0.52835647],
     [ 0.4215251 ,  0.45017551]],

    [[ 0.92814219,  0.96677647],
     [ 0.85304703,  0.52351845],
     [ 0.19981397,  0.27417313]],

    [[ 0.60659855,  0.00533165],
     [ 0.10820313,  0.49978937],
     [ 0.34144279,  0.94630077]]
    ])


print("iamge2vector:: " + str(image2vector(pic1)))

(3, 3, 2)
iamge2vector:: [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]
